// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxCfmol5AddHC1wi-RQcgTzYnKEGuSvIU',
    appId: '1:85207850072:web:07e41335f5b55396e93e2d',
    messagingSenderId: '85207850072',
    projectId: 'retrovault121',
    authDomain: 'retrovault121.firebaseapp.com',
    storageBucket: 'retrovault121.appspot.com',
    measurementId: 'G-5XT4YN0TC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGNZSfYKfIdscxM8azjpj8w89cQr9Qar4',
    appId: '1:85207850072:android:35543cd375ed7369e93e2d',
    messagingSenderId: '85207850072',
    projectId: 'retrovault121',
    storageBucket: 'retrovault121.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI7MIF6BOiWMLj32BUDWU8zYXcKhfZYIo',
    appId: '1:85207850072:ios:0f1ab2d0d419ac76e93e2d',
    messagingSenderId: '85207850072',
    projectId: 'retrovault121',
    storageBucket: 'retrovault121.appspot.com',
    iosBundleId: 'com.example.retro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI7MIF6BOiWMLj32BUDWU8zYXcKhfZYIo',
    appId: '1:85207850072:ios:0f1ab2d0d419ac76e93e2d',
    messagingSenderId: '85207850072',
    projectId: 'retrovault121',
    storageBucket: 'retrovault121.appspot.com',
    iosBundleId: 'com.example.retro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxCfmol5AddHC1wi-RQcgTzYnKEGuSvIU',
    appId: '1:85207850072:web:a114f37cc0abab92e93e2d',
    messagingSenderId: '85207850072',
    projectId: 'retrovault121',
    authDomain: 'retrovault121.firebaseapp.com',
    storageBucket: 'retrovault121.appspot.com',
    measurementId: 'G-1DKBRC661Y',
  );
}
