// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAER0LbNjoIp-m_8s0nIu_NwXEu4z6vBtQ',
    appId: '1:209277499518:web:ce3649547a487f40de802f',
    messagingSenderId: '209277499518',
    projectId: 'retrovault-c3010',
    authDomain: 'retrovault-c3010.firebaseapp.com',
    storageBucket: 'retrovault-c3010.appspot.com',
    measurementId: 'G-XTCRCMZ8NB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDevKU8kBxqobSILIk4mEhqqe_L6ZF8Mzc',
    appId: '1:209277499518:android:42266cdb697aeea9de802f',
    messagingSenderId: '209277499518',
    projectId: 'retrovault-c3010',
    storageBucket: 'retrovault-c3010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApVbsODVT0Q6rbi0h1ACV1iiGwoUL7X4g',
    appId: '1:209277499518:ios:9b122327b888002cde802f',
    messagingSenderId: '209277499518',
    projectId: 'retrovault-c3010',
    storageBucket: 'retrovault-c3010.appspot.com',
    iosBundleId: 'com.example.retro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApVbsODVT0Q6rbi0h1ACV1iiGwoUL7X4g',
    appId: '1:209277499518:ios:9b122327b888002cde802f',
    messagingSenderId: '209277499518',
    projectId: 'retrovault-c3010',
    storageBucket: 'retrovault-c3010.appspot.com',
    iosBundleId: 'com.example.retro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAER0LbNjoIp-m_8s0nIu_NwXEu4z6vBtQ',
    appId: '1:209277499518:web:30f5675d2c0201ecde802f',
    messagingSenderId: '209277499518',
    projectId: 'retrovault-c3010',
    authDomain: 'retrovault-c3010.firebaseapp.com',
    storageBucket: 'retrovault-c3010.appspot.com',
    measurementId: 'G-Z58C8GB5P7',
  );

}